'use client'

import Link from 'next/link'
import ReactMarkdown from 'react-markdown'
import { useState, useRef, useEffect } from 'react'
import dynamic from 'next/dynamic'

const VoiceQuiz = dynamic(() => import('@/components/quiz/VoiceQuiz'), { ssr: false })

const LESSON_25_SLIDES = [
  {
    id: 1,
    title: "",
    content: `What happens in that moment when a thought **"comes to you"**? Not when you construct it brick by brick, but when it appears suddenly, like an **epiphany**?`,
    emoji: "📖",
    duration: 20000
  },
  {
    id: 2,
    title: "",
    content: `Our brain is a **supercomputer**. Billions of possible **"thoughts"**. How do I manage to choose the right one? 

> The "I" that is supposed to choose the thought is itself a product of the thinking process. A closed loop.`,
    emoji: "🔍",
    duration: 20000
  },
  {
    id: 3,
    title: "",
    content: `To break this cycle, let's imagine that the **"I"** is not the author of thoughts, but their **radio receiver**. 

Here's the radio analogy:

- **"Airwaves"** — an infinite reservoir of abstraction combinations generated by the brain
- **"Radio station"** — a specific thought with a unique **"frequency"**
- **"Local oscillator"** — a brain structure whose frequency is unique to each person
- **"Resonance"** — the moment when a thought's frequency matches our local oscillator
- **"Demodulation"** — the awareness of thought, its formation into words`,
    emoji: "💡",
    duration: 43360
  },
  {
    id: 4,
    title: "",
    content: `> We do not compose thoughts. We catch them.`,
    emoji: "📊",
    duration: 20000
  },
  {
    id: 5,
    title: "",
    content: `To understand this mechanism, let us imagine our **consciousness** as consisting of two interconnected, but fundamentally different circuits.`,
    emoji: "🎯",
    duration: 20000
  },
  {
    id: 6,
    title: "",
    content: `The first is the **analog circuit**. This is the world of immediate, embodied, sensory experience. The taste of an apple. Pain from a burn. The warmth of the sun. Vague melancholy or sudden joy. 

The language here is not words, but lived experiences. The bandwidth is small—dozens of states. But each one is a deeply rooted, energetically saturated life lesson. 

> This is the inner core, the foundation of personality. We can call this **proto-knowledge**.`,
    emoji: "🧠",
    duration: 34960
  },
  {
    id: 7,
    title: "",
    content: `The second circuit is **digital**. This is the world of **abstractions**, **signs**, and **concepts**. Words, numbers, formulas, social roles, logical chains. The language is precise and communicable. 

It has **colossal bandwidth** — billions of combinations per second. But by itself — it is empty. 

> The word "pain" is simply a set of sounds. The digit "5" is an abstraction without an object.

This is an **interface**.`,
    emoji: "✨",
    duration: 31680
  },
  {
    id: 8,
    title: "",
    content: `Where does the **thought** that we recognize as our own originate? **Thinking** is not the work of a single circuit. It is a process of **resonant dialogue** between them. 

The **digital circuit** proposes options, builds models: "what if...", "this is similar to...". Each such model is projected onto the **analogical core**. And then comes the moment of truth — **resonance**.

> If the model coincides with some pattern, some cluster of experience in the analogical circuit, resonance occurs — a sharp amplification of the signal.

This amplified, "energized" model breaks through into consciousness as a **conscious thought**, as an **insight**. If there is no resonance, the model fades away — it's just empty mental play, unimportant information.`,
    emoji: "📝",
    duration: 56000
  },
  {
    id: 9,
    title: "",
    content: `The **digital system** poses questions, while the **analog system** votes with resources of **attention** and **emotional energy**. 

> The winner gains the right to become a conscious thought.`,
    emoji: "🌟",
    duration: 20000
  },
  {
    id: 10,
    title: "",
    content: `What is this **"analog core"** that resonates so selectively? It is our unique internal resonator, or **cognitive profile**. It is tuned by three factors:

1. **Heredity** — the given "factory settings," the characteristics of our nervous system

2. **Cultural code** — the language, values, and concepts of the society in which we grew up

3. **Personal experience** — the most important factor

> Each experience, success and failure finely tunes our resonator.`,
    emoji: "🔮",
    duration: 34640
  },
  {
    id: 11,
    title: "",
    content: `If thought describes a reality that is **preferable to the current one** — it becomes **desire**. And desire, which we embody through action, becomes a **goal**.

> It follows that **goal-directed activity** is a direct continuation of thinking.`,
    emoji: "📖",
    duration: 20000
  },
  {
    id: 12,
    title: "",
    content: `If **thinking is resonance**, then how do we develop it? The answer becomes crystal clear. Traditional rote learning is a dead end. It's loading the digital circuit with empty symbols that have no connection to experience. 

> No material for resonance means no amplification. The student "doesn't want" to learn.`,
    emoji: "🔍",
    duration: 25680
  },
  {
    id: 13,
    title: "",
    content: `**The effective approach is learning through experience.** First, you need to create a situation where the student feels the problem, acts, and experiences it firsthand. At the moment of peak experience, provide the name, formula, or rule.

> Then living experience connects with abstract symbols. Resonance occurs! The "wow!" effect emerges. Knowledge becomes "one's own."`,
    emoji: "💡",
    duration: 27680
  },
  {
    id: 14,
    title: "",
    content: `> The educator's task is to **organize an encounter** between the student's **analog experience** and the **digital label of knowledge**.`,
    emoji: "📊",
    duration: 20000
  },
  {
    id: 15,
    title: "",
    content: `Now let us pose a **philosophical question**: where did this very **consciousness** that is capable of resonating come from? Let us examine this through the lens of ancient texts, as the author does.`,
    emoji: "🎯",
    duration: 20000
  },
  {
    id: 16,
    title: "",
    content: `> "In the beginning God created the heavens and the earth" — says the Bible.

Here, **heaven** and **earth** are not the familiar concepts we know, but **abstract notions**. 

**Earth** represents the **observable** — the world. **Heaven** represents the **unobservable** — nothingness.`,
    emoji: "🧠",
    duration: 20000
  },
  {
    id: 17,
    title: "",
    content: `> "And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters."

What is **water**? In the beginning, the boundary between earth and sky is still indistinguishable, and both remain unobservable. Therefore, they are both something unified, **boundless**, **formless**, **indistinguishable**—something that is called water.

In modern vocabulary, this is **Being**.`,
    emoji: "✨",
    duration: 33840
  },
  {
    id: 18,
    title: "",
    content: `**The Spirit of God** moved upon the face of the waters. **The Spirit of God** belongs neither to heaven nor to earth. 

> The first trinity: **God = Water + Holy Spirit**.`,
    emoji: "📝",
    duration: 20000
  },
  {
    id: 19,
    title: "",
    content: `> "And God said, Let there be light. And there was light."

The **Spirit of God**, which moved upon the face of the waters, having fertilized the **primordial waters** (Genesis), gives birth to light. 

But what is this light? Here it is not the physical light from the sun. The sun does not yet exist. Moreover, nothing observable exists, since there is no observer.`,
    emoji: "🌟",
    duration: 27440
  },
  {
    id: 20,
    title: "",
    content: `**Light** is the ability to abstract. **Light** is that through which humans distinguish and observe. Animals have vision; they can see. But this is merely a reaction to physical light. Animals cannot **observe**. 

> To observe means to distinguish the boundaries between the observable (**the World**) and the unobservable (**Nothingness**).

This is only possible when one possesses the ability to look from the outside, only when one possesses the **ability to abstract**.`,
    emoji: "🔮",
    duration: 37280
  },
  {
    id: 21,
    title: "",
    content: `> "And God saw the light, that it was good, and God divided the light from the darkness."

So who saw? **God**? But God is the **absolute All**. He is **omniscient** and always knew that light was good. 

To see means to distinguish boundaries, to look from the outside. But this violates the principle of God's **boundlessness and unity**. Yet man does not exist yet. Therefore it is said that **God saw**.

**God saw not in the ordinary sense.** To distinguish what is good and what is not good — only God can do this. Only He knows the **ultimate purpose of man**.`,
    emoji: "📖",
    duration: 41920
  },
  {
    id: 22,
    title: "",
    content: `> "And God said: Let there be a firmament in the midst of the waters, and let it divide the waters from the waters. And God made the firmament, and divided the waters which were under the firmament from the waters which were above the firmament."

The **firmament** is that boundary which separated **World** from **Nothingness** after the appearance of light (the capacity to abstract). 

It is precisely about this light that discourse will arise when speaking of the end of the world.`,
    emoji: "🔍",
    duration: 37520
  },
  {
    id: 23,
    title: "",
    content: `Through **light**, both water and the **observer himself** — **Man** — came into being. After all, to see the World within its boundaries, beyond which lies Nothingness, one can only do so by being outside both this World and this Nothingness. 

> The Quran states: "He is the One Who created man from water..."`,
    emoji: "💡",
    duration: 22640
  },
  {
    id: 24,
    title: "",
    content: `No one guarantees that there are no other beings with a different **metric**. They will split the same **Being** along different boundaries. Within one **Being**, multiple different **Worlds** potentially exist.`,
    emoji: "📊",
    duration: 20000
  },
  {
    id: 25,
    title: "",
    content: `There was **One** (the Almighty), who created **Two** (the Spirit of God and water). **Two** gave birth to light and through it **Three**: the World, Nothing, and Man. **Three** gave birth to everything and, ultimately, the **Word** — and the **Word** was God.`,
    emoji: "🎯",
    duration: 20000
  },
  {
    id: 26,
    title: "",
    content: `We are not **processors** coldly sorting through data. We are unique **resonators of meaning**. Our thoughts are gifts that we discover within ourselves when a signal finds resonance in our experience. 

> And this experience itself is our unique part in the great act of creation, where each of us, capable of observation, becomes a **co-creator** of the world's boundaries.`,
    emoji: "🧠",
    duration: 28720
  }
];

export default function Lesson25Page() {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [progress, setProgress] = useState(0);
  const [audioError, setAudioError] = useState(false);
  const [showQuiz, setShowQuiz] = useState(false);
  const audioRef = useRef<HTMLAudioElement>(null);
  const timerRef = useRef<NodeJS.Timeout | null>(null);

  const totalSlides = LESSON_25_SLIDES.length;

  useEffect(() => {
    if (!isPlaying) return;

    const audioFile = `/audio/lesson25/slide${currentSlide + 1}.mp3`;
    if (audioRef.current) {
      audioRef.current.src = audioFile;
      audioRef.current.play().catch(() => {
        setAudioError(true);
        const duration = LESSON_25_SLIDES[currentSlide].duration;
        timerRef.current = setTimeout(() => {
          if (currentSlide < totalSlides - 1) {
            setCurrentSlide(prev => prev + 1);
          } else {
            setIsPlaying(false);
          }
        }, duration);
      });
    }

    return () => {
      if (timerRef.current) clearTimeout(timerRef.current);
    };
  }, [currentSlide, isPlaying, totalSlides]);

  useEffect(() => {
    if (!isPlaying || !audioError) return;
    
    const duration = LESSON_25_SLIDES[currentSlide].duration;
    const interval = setInterval(() => {
      setProgress(prev => {
        if (prev >= 100) return 0;
        return prev + (100 / (duration / 100));
      });
    }, 100);

    return () => clearInterval(interval);
  }, [isPlaying, audioError, currentSlide]);

  useEffect(() => {
    if (!isPlaying || audioError) return;
    
    const interval = setInterval(() => {
      if (audioRef.current && audioRef.current.duration) {
        const percent = (audioRef.current.currentTime / audioRef.current.duration) * 100;
        setProgress(percent);
      }
    }, 100);

    return () => clearInterval(interval);
  }, [isPlaying, audioError]);

  const handleAudioEnded = () => {
    if (currentSlide < totalSlides - 1) {
      setCurrentSlide(prev => prev + 1);
      setProgress(0);
    } else {
      setIsPlaying(false);
      setProgress(100);
    }
  };

  const togglePlay = () => {
    if (isPlaying) {
      audioRef.current?.pause();
      if (timerRef.current) clearTimeout(timerRef.current);
      setIsPlaying(false);
    } else {
      setIsPlaying(true);
      setProgress(0);
    }
  };

  const goToSlide = (index: number) => {
    if (timerRef.current) clearTimeout(timerRef.current);
    setCurrentSlide(index);
    setProgress(0);
    if (isPlaying) setAudioError(false);
  };

  const currentSlideData = LESSON_25_SLIDES[currentSlide];

  return (
    <div className="min-h-screen bg-stone-50">
      <audio ref={audioRef} onEnded={handleAudioEnded} onError={() => setAudioError(true)} />
      
      <header className="bg-stone-800 text-stone-100 border-b-4 border-amber-700">
        <div className="max-w-5xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <Link href="/lessons" className="text-stone-400 hover:text-white flex items-center gap-2 text-sm">← Back to Course</Link>
            <div className="text-center">
              <h1 className="text-lg font-serif">Algorithms of Thinking and Cognition</h1>
              <p className="text-stone-400 text-sm">Lecture 25</p>
            </div>
            <div className="text-stone-400 text-sm">{currentSlide + 1} / {totalSlides}</div>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-10">
        <div className="text-center mb-10">
          <span className="text-5xl mb-4 block">{currentSlideData.emoji}</span>
          <h2 className="text-3xl font-serif text-stone-800 mb-2">{currentSlideData.title}</h2>
          <div className="w-24 h-1 bg-amber-700 mx-auto"></div>
        </div>

        <article className="bg-white rounded-lg shadow-lg border border-stone-200 p-8 md:p-12 mb-8">
          <div className="prose prose-stone prose-lg max-w-none">
            <ReactMarkdown
              components={{
                p: ({children}) => <p className="text-stone-700 leading-relaxed mb-5 text-lg">{children}</p>,
                strong: ({children}) => <strong className="text-stone-900 font-semibold">{children}</strong>,
                blockquote: ({children}) => <blockquote className="border-l-4 border-amber-700 pl-6 my-6 italic text-stone-600 bg-amber-50 py-4 pr-4 rounded-r">{children}</blockquote>,
              }}
            >
              {currentSlideData.content}
            </ReactMarkdown>
          </div>
        </article>

        <div className="bg-white rounded-lg shadow border border-stone-200 p-6 mb-6">
          <div className="flex items-center justify-between mb-3">
            <span className="text-sm text-stone-500 font-medium">Slide Progress</span>
            <span className="text-sm text-stone-500">{Math.round(progress)}%</span>
          </div>
          <div className="h-2 bg-stone-200 rounded-full overflow-hidden">
            <div className="h-full bg-amber-700 transition-all duration-300 rounded-full" style={{ width: `${progress}%` }} />
          </div>
        </div>

        <div className="flex items-center justify-center gap-6 mb-10">
          <button onClick={() => goToSlide(Math.max(0, currentSlide - 1))} disabled={currentSlide === 0} className="px-5 py-2 rounded border border-stone-300 text-stone-600 disabled:opacity-30 hover:bg-stone-100 transition font-medium">← Previous</button>
          <button onClick={togglePlay} className="px-8 py-3 rounded-lg bg-amber-700 text-white font-semibold hover:bg-amber-800 transition shadow-md">{isPlaying ? '⏸ Pause' : '▶ Play Lecture'}</button>
          <button onClick={() => goToSlide(Math.min(totalSlides - 1, currentSlide + 1))} disabled={currentSlide === totalSlides - 1} className="px-5 py-2 rounded border border-stone-300 text-stone-600 disabled:opacity-30 hover:bg-stone-100 transition font-medium">Next →</button>
        </div>

        <div className="bg-gradient-to-r from-amber-600 to-amber-800 rounded-lg shadow-lg p-6 mb-10 text-center">
          <h3 className="text-xl font-bold text-white mb-2">🎤 Ready to Test Your Knowledge?</h3>
          <p className="text-amber-100 mb-4">Take a voice quiz with AI-generated questions</p>
          <button onClick={() => setShowQuiz(true)} className="px-8 py-3 bg-white text-amber-700 rounded-lg font-bold hover:bg-amber-50 transition shadow-md">Start Voice Quiz</button>
        </div>

        <div className="bg-white rounded-lg shadow border border-stone-200 p-6">
          <h3 className="text-sm font-semibold text-stone-500 uppercase tracking-wide mb-4">Lecture Sections</h3>
          <div className="grid grid-cols-4 md:grid-cols-10 gap-2">
            {LESSON_25_SLIDES.map((slide, index) => (
              <button key={slide.id} onClick={() => goToSlide(index)} className={`p-3 rounded text-sm font-medium transition ${index === currentSlide ? 'bg-amber-700 text-white' : index < currentSlide ? 'bg-amber-100 text-amber-800 hover:bg-amber-200' : 'bg-stone-100 text-stone-500 hover:bg-stone-200'}`} title={slide.title}>{index + 1}</button>
            ))}
          </div>
        </div>
      </main>

      {showQuiz && <VoiceQuiz lessonId={25} lessonTitle="THINKING AS RESONANCE AND THE BIRTH OF THE WORLD" onClose={() => setShowQuiz(false)} />}

      <footer className="bg-stone-800 text-stone-400 py-6 mt-16 border-t-4 border-amber-700">
        <div className="max-w-4xl mx-auto px-6">
          <div className="flex justify-between items-center">
            <Link href="/lessons/24" className="hover:text-white transition">← Lecture 24</Link>
            <span className="text-stone-500 text-sm font-serif">Lecture 25</span>
            <Link href="/lessons" className="hover:text-white transition">All Lessons →</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
